---
services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    user: "${UID:?run `make prepare`}:${GID:?run `make prepare`}"
    volumes:
      - "./rollup.xml:/etc/clickhouse-server/config.d/rollup.xml"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./data/clickhouse:/var/lib/clickhouse"
    networks:
      - graphite-clickhouse-tldr
    cap_add: &caps
      - SYS_PTRACE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_NICE
  carbon-clickhouse:
    image: ghcr.io/go-graphite/carbon-clickhouse:0.11.8
    user: "${UID:?run `make prepare`}:${GID:?run `make prepare`}"
    volumes:
      - "./data:/data"
      - "./carbon-clickhouse.conf:/etc/carbon-clickhouse/carbon-clickhouse.conf"
    ports:
      - "2003:2003"  # plain tcp
      - "2003:2003/udp"  # plain udp
      - "2004:2004"  # pickle
      - "2006:2006"  # prometheus remote write
    networks:
      - graphite-clickhouse-tldr
  graphite-clickhouse:
    image: ghcr.io/go-graphite/graphite-clickhouse:0.14.0
    volumes:
      - "./rollup.xml:/etc/graphite-clickhouse/rollup.xml"
      - "./graphite-clickhouse.conf:/etc/graphite-clickhouse/graphite-clickhouse.conf"
    ports:
      - "9090:9090"  # carbonapi/graphite-web endpoint
      - "9092:9092"  # prometheus endpoint
    networks:
      - graphite-clickhouse-tldr
  carbonapi:
    image: ghcr.io/go-graphite/carbonapi:0.17.0
    volumes:
      - "./carbonapi.yml:/etc/carbonapi.yml"
      - "./graphTemplates.yaml:/etc/graphTemplates.yaml"
    networks:
      - graphite-clickhouse-tldr
    ports:
      - "7080:7080"  # http ui
  grafana:
    user: "${UID:?run `make prepare`}:${GID:?run `make prepare`}"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "tldr"
    image: grafana/grafana:11.3.0-ubuntu
    volumes:
      - "./data/grafana:/var/lib/grafana"
      - "./grafana-graphite-datasource.yaml:/etc/grafana/provisioning/datasources/graphite.yaml"
    networks:
      - graphite-clickhouse-tldr
    ports:
      - "80:3000"  # http ui

networks:
  graphite-clickhouse-tldr:
